{% set name = "torch-hd" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff93f5f0f3deef23bd791ec132f8531f8c73275b2c52178dd19cba07a7bc9cb2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - pandas
    - python >=3.6
    - requests
    - pytorch

test:
  imports:
    - torchhd
    - torchhd.functional
    - torchhd.embeddings
    - torchhd.structures
    - torchhd.datasets

  commands:
    - pip check

  requires:
    - pip

about:
  home: https://github.com/hyperdimensional-computing/torchhd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Torchhd is a Python library for Hyperdimensional Computing

extra:
  recipe-maintainers:
    - dheyay
